# Default values for slate-portal.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# harbor is the set of hostname, project id, etc. related to OSG Harbor
harbor:
  hostname: 'hub.opensciencegrid.org'
  projectID: 'slate'


# apiPort is the port for the SLATE API
apiPort: '18080'

# globusAuthLogoutURI is the URI used for logging out via globus
globusAuthLogoutURI: 'https://auth.globus.org/v2/web/logout'
# globusRedirectURIScheme is the scheme for redirecting to Globus
globusRedirectURIScheme: 'https'

# portalPort is the port for the SLATE Portal
portalPort: '5050'

# opentelemetryCollector gives the uri for the opentelemetry collector
opentelemetryCollector: "https://otel-collector.telemetry.slateci.io:443/"
