apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-conf-secret" (include "helm-slate-portal.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-slate-portal.labels" . | nindent 4 }}
type: Opaque
stringData:
  content: |
    GLOBUS_AUTH_LOGOUT_URI = '{{ .Values.globusAuthLogoutURI }}'
    GLOBUS_REDIRECT_URI_SCHEME = '{{ .Values.globusRedirectURIScheme }}'
    MAILGUN_API_TOKEN = '{{ .Values.mailgunAPIToken }}'
    PORTAL_CLIENT_ID = '{{ .Values.portalClientID }}'
    PORTAL_CLIENT_SECRET = '{{ .Values.portalClientSecret }}'
    PORTAL_VERSION = '{{ .Chart.AppVersion }}'
    SECRET_KEY = '{{ .Values.secretKey }}'
    SERVER_NAME = '{{ .Values.portalEndpoint }}'
    SLATE_API_ENDPOINT = 'https://{{ .Values.apiEndpoint }}'
    SLATE_API_TOKEN = '{{ .Values.apiToken }}'
