---
- name: Create key pair for the server
  openssl_privatekey:
    path: "{{ slate_certificate.key_file }}"
    size: 2048

- name: Create certificate signing request
  openssl_csr:
    common_name: "slate_portal"
    country_name: "US"
    email_address: "slate@slateci.io"
    locality_name: "Salt Lake City"
    organization_name: "University of Utah"
    path: "{{ slate_certificate.chain_file }}"
    subject_alt_name:
      - "DNS:*.{{ slate_hostname }}"
      - "DNS:{{ slate_hostname }}"
    privatekey_path: "{{ slate_certificate.key_file }}"

- name: Create self-signed certificate
  openssl_certificate:
    csr_path: "{{ slate_certificate.chain_file }}"
    path: "{{ slate_certificate.file }}"
    provider: selfsigned
    privatekey_path: "{{ slate_certificate.key_file }}"
