---
- name: Create key pair for the server
  openssl_privatekey:
    path: "/etc/ssl/server.rsa"
    size: 2048

- name: Create certificate signing request
  openssl_csr:
    common_name: "slate_portal"
    country_name: "US"
    email_address: "slate@slateci.io"
    locality_name: "Salt Lake City"
    organization_name: "University of Utah"
    path: "/etc/ssl/server.csr"
    subject_alt_name:
      - "DNS:*.{{ slate_hostname }}"
      - "DNS:{{ slate_hostname }}"
    privatekey_path: "/etc/ssl/server.rsa"

- name: Create self-signed certificate
  openssl_certificate:
    csr_path: "/etc/ssl/server.csr"
    path: "/etc/ssl/server.crt"
    provider: selfsigned
    privatekey_path: "/etc/ssl/server.rsa"
