---
- name: Checking if SLATE cert already exists
  stat:
    path: "{{ slate_certificate.file }}"
  register: slate_cert_file

- name: Ensure certbot webroot directory exists
  file:
    path: "{{ certbot_webroot }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not slate_cert_file.stat.exists

- name: Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal
    job: "certbot renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
