---
- name: Checking if SLATE cert already exists
  stat:
    path: "{{ slate_certificate.file }}"
  register: slate_cert_file

- name: Ensure certbot pre/post hook directories exist
  file:
    path: "/etc/letsencrypt/renewal-hooks/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - pre
    - post

- name : Create certbot pre hook to stop services
  template:
    src: "templates/certbot-stop-services.j2"
    dest: "/etc/letsencrypt/renewal-hooks/pre/stop_services"
    owner: root
    group: root
    mode: 0750
  when:
    - certbot_create_standalone_stop_services is defined
    - certbot_create_standalone_stop_services

- name : Create certbot post hook to start services
  template:
    src: "templates/certbot-start-services.j2"
    dest: "/etc/letsencrypt/renewal-hooks/post/start_services"
    owner: root
    group: root
    mode: 0750
  when:
    - certbot_create_standalone_stop_services is defined
    - certbot_create_standalone_stop_services

- name: Generate new certificate if one doesn't exist.
  command: "{{ certbot_create_command }}"
  when: not slate_cert_file.stat.exists

- name: Add cron job for certbot renewal
  cron:
    name: Certbot automatic renewal
    job: "certbot renew {{ certbot_auto_renew_options }}"
    minute: "{{ certbot_auto_renew_minute }}"
    hour: "{{ certbot_auto_renew_hour }}"
    user: "{{ certbot_auto_renew_user }}"
