---

- name: Enable firewalld.service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled
    immediate: yes

- name: Permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled
    immediate: yes

- name: Block traffic in default zone on port 3031/tcp
  ansible.posix.firewalld:
    port: 3031/tcp
    permanent: yes
    state: disabled
    immediate: yes
  when: not slate_debug

- name: Permit traffic in default zone on port 3031/tcp
  ansible.posix.firewalld:
    port: 3031/tcp
    permanent: yes
    state: enabled
    immediate: yes
  when: slate_debug
