---
- name: Add systemd nginx configuration
  template:
    src: "templates/nginx.service.j2"
    dest: "/etc/systemd/system/nginx.service"
    owner: root
    group: root
    mode: 0644
  notify: portal_restart_services

- name: Add nginx configuration
  template:
    src: "templates/nginx.conf.j2"
    dest: "/etc/nginx/nginx.conf"
    owner: root
    group: root
    mode: 0644
  notify: portal_restart_services

- name: Start nginx.service
  service:
    name: nginx
    state: started
    enabled: true
