---
- name: Install extra repos via system package manager
  package:
    name:
      - epel-release
    state: present

- name: Install general packages/dependencies via system package manager
  package:
    name:
      - git
      - nginx
      - python-setuptools
      - python3
      - python3-devel
      - uwsgi
      - uwsgi-plugin-python3
      - which
    state: present

- name: Install general packages/dependencies via system package manager (live)
  package:
    name:
      - certbot
      - crontab
    state: present
  when: not slate_debug
