---
- name: Install extra repos via system package manager
  package:
    name:
      - epel-release
    state: present

- name: Install general packages/dependencies via system package manager
  package:
    name:
      - git
      - python-setuptools
      - python3
    state: present

- name: Update pip
  pip:
    name: pip
    executable: pip3
    extra_args: --upgrade

- name: Install virtualenv python package
  pip:
    name: virtualenv
    executable: pip3

- name: Create group for running uwsgi
  group:
    name: uwsgi
    state: present

- name: Create user for running uwsgi
  user:
    name: uwsgi
    state: present
    shell: "/sbin/nologin"
    group: uwsgi
    home: "/var/run/uwsgi"
    system: true
