---
- name: Checking SLATE install directory
  stat:
    path: "{{ slate_install.dest }}"
  register: slate_install_path

- name: Creating SLATE install directory
  file:
    path: "{{ slate_install.dest }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: slate_install_path.stat.exists == false

- name: Add SLATE configuration
  template:
    src: "templates/slate.ini.j2"
    dest: "{{ slate_install.dest }}/slate.ini"
    owner: root
    group: root
    mode: 0644

- name: Clone the SLATE Portal Git repository
  git:
    repo: "{{ slate_git.repo }}"
    dest: "{{ slate_git.dest }}"
    depth: 1 # Centos7's git cannot shallow clone but leaving for future OS compatibility.
    single_branch: yes
    version: "{{ slate_git.version }}"
    update: yes
    force: yes

- name: Install pip requirements to venv
  pip:
    requirements: "{{ slate_git.dest }}/requirements.txt"
    virtualenv: "{{ slate_install.dest }}/venv"
    virtualenv_command: "/usr/local/bin/virtualenv"
    virtualenv_python: python3.6

- name: Changing ownership of SLATE Portal Git repository to uwsgi:uwsgi 0644
  file:
    path: "{{ slate_git.dest }}"
    state: directory
    recurse: yes
    owner: uwsgi
    group: uwsgi
    mode: 0644

- name: Changing permissions of SLATE Portal Git repository top directory to 0755
  file:
    path: "{{ slate_git.dest }}"
    state: directory
    recurse: no
    mode: 0755

- name: Finding all subdirectories in SLATE Portal Git repository
  find:
    paths:
      - "{{ slate_git.dest }}"
    recurse: true
    file_type: directory
  register: slate_portal_subdirs

- name: Changing permissions of SLATE Portal Git repository subdirectories to 0755
  file:
    path: "{{ item.path }}"
    mode: 0755
  loop: "{{ slate_portal_subdirs.files }}"
  loop_control:
    label: "{{ item.path }}"


- name: Add SLATE Portal instance directory
  file:
    path: "{{ slate_git.dest }}/instance"
    state: directory
    owner: uwsgi
    group: uwsgi
    mode: 0755

- name: Add portal configuration
  template:
    src: "templates/portal.conf.j2"
    dest: "{{ slate_git.dest }}/instance/portal.conf"
    owner: uwsgi
    group: uwsgi
    mode: 0644

- name: Make run_portal.py executable
  file:
    path: "{{ slate_git.dest }}/run_portal.py"
    state: file
    owner: uwsgi
    group: uwsgi
    mode: 0755
