---
- name: Checking SLATE root directory
  stat:
    path: "{{ slate_root.path }}"
  register: slate_root_directory

- name: Creating SLATE root directory
  file:
    path: "{{ slate_root.path }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: slate_root_directory.stat.exists == false

- name: Add SLATE configuration
  template:
    src: "templates/slate.ini.j2"
    dest: "{{ slate_root.path }}/slate.ini"
    owner: root
    group: root
    mode: 0644

- name: Clone the SLATE Portal Git repository
  git:
    repo: "{{ slate_portal.repo }}"
    dest: "{{ slate_portal.path }}"
    depth: 1
    single_branch: yes
    version: master
    update: no

- name: Changing ownership of SLATE Portal Git repository to uwsgi:uwsgi
  file:
    path: "{{ slate_portal.path }}"
    state: directory
    recurse: yes
    owner: uwsgi
    group: uwsgi
    mode: 0644

- name: Changing permissions of SLATE Portal Git repository top directory for centos/uwsgi
  file:
    path: "{{ slate_portal.path }}"
    state: directory
    recurse: no
    owner: uwsgi
    group: uwsgi
    mode: 0755

- name: Install pip requirements to venv
  pip:
    requirements: "{{ slate_portal.path }}/requirements.txt"
    virtualenv: "{{ slate_root.path }}/venv"
    virtualenv_command: "/usr/local/bin/virtualenv"
    virtualenv_python: python3.6

- name: Add SLATE Portal instance directory
  file:
    path: "{{ slate_portal.path }}/instance"
    state: directory
    owner: uwsgi
    group: uwsgi
    mode: 0644

- name: Make run_portal.py executable
  file:
    path: "{{ slate_portal.path }}/run_portal.py"
    state: file
    owner: uwsgi
    group: uwsgi
    mode: 0755

- name: Add portal configuration
  template:
    src: "templates/portal.conf.j2"
    dest: "{{ slate_portal.path }}/instance/portal.conf"
    owner: root
    group: root
    mode: 0644
