---
- name: Checking if SLATE install directory already exists
  stat:
    path: "{{ slate_install_dest }}"
  register: slate_install_path

- name: Ensure SLATE install directory exists
  file:
    path: "{{ slate_install_dest }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not slate_install_path.stat.exists

- name: Add SLATE configuration
  template:
    src: "templates/slate.ini.j2"
    dest: "{{ slate_install_dest }}/slate.ini"
    owner: uwsgi
    group: uwsgi
    mode: 0644
  notify: portal_restart_services

- name: Clone the SLATE Portal Git repository
  git:
    repo: "https://github.com/slateci/slate-portal.git"
    dest: "{{ slate_git_dest }}"
    depth: 1 # Centos7's git cannot shallow clone but leaving for future OS compatibility.
    single_branch: yes
    version: "{{ slate_git_version }}"
    force: yes
    update: yes

- name: Housekeeping on Git clone artifacts
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ slate_git_dest }}/.dockerignore"
    - "{{ slate_git_dest }}/.editorconfig"
    - "{{ slate_git_dest }}/.github/"
    - "{{ slate_git_dest }}/ansible/"
    - "{{ slate_git_dest }}/Dockerfile"
    - "{{ slate_git_dest }}/docker-entrypoint.sh"
    - "{{ slate_git_dest }}/docs/"
    - "{{ slate_git_dest }}/LICENSE"
    - "{{ slate_git_dest }}/notebook/"
    - "{{ slate_git_dest }}/README.md"
    - "{{ slate_git_dest }}/run_portal_docker.py"
    - "{{ slate_git_dest }}/Vagrantfile"

- name: Install pip requirements to venv
  pip:
    requirements: "{{ slate_git_dest }}/requirements.txt"
    virtualenv: "{{ slate_install_dest }}/venv"
    virtualenv_command: "/usr/local/bin/virtualenv"
    virtualenv_python: python3.6

- name: Changing ownership of SLATE Portal Git repository to uwsgi:uwsgi
  file:
    path: "{{ slate_git_dest }}"
    state: directory
    recurse: yes
    owner: uwsgi
    group: uwsgi

- name: Changing ownership of SLATE Portal Git repository .git directory to root:root
  file:
    path: "{{ slate_git_dest }}/.git/"
    state: directory
    recurse: yes
    owner: root
    group: root
    mode: 0644

- name: Add portal configuration
  template:
    src: "templates/portal.conf.j2"
    dest: "{{ slate_git_dest }}/instance/portal.conf"
    owner: uwsgi
    group: uwsgi
    mode: 0644
  notify: portal_restart_services

- name: Make run_portal.py executable
  file:
    path: "{{ slate_git_dest }}/run_portal.py"
    state: file
    owner: uwsgi
    group: uwsgi
    mode: 0755
  notify: portal_restart_services
