---
- name: Create group for running SLATE Portal
  group:
    name: slate-portal
    state: present

- name: Create user for running SLATE Portal
  user:
    name: slate-portal
    state: present
    shell: "/sbin/nologin"
    group: slate-portal
    groups: ""
    home: "/var/run/slate-portal"
    system: true

- name: Add uwsgi to slate-portal group
  user:
    name: uwsgi
    groups: "uwsgi,slate-portal"
