---
- name: Add systemd uwsgi configuration
  template:
    src: "templates/uwsgi.service.j2"
    dest: "/etc/systemd/system/uwsgi.service"
    owner: root
    group: root
    mode: 0644
  notify: portal_restart_services

- name: Add uwsgi configuration
  template:
    src: "templates/uwsgi.ini.j2"
    dest: "/etc/uwsgi.ini"
    owner: root
    group: root
    mode: 0644
  notify: portal_restart_services
