---
- name: Checking if uWSGI log directory already exists
  stat:
    path: "/var/log/uwsgi"
  register: uwsgi_log_path

- name: Ensure uWSGI log directory exists
  file:
    path: "/var/log/uwsgi"
    state: directory
    owner: uwsgi
    group: uwsgi
    mode: 0755
  when: not uwsgi_log_path.stat.exists

- name: Add systemd uwsgi.service
  template:
    src: "templates/systemd/uwsgi.service.j2"
    dest: "/etc/systemd/system/uwsgi.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - systemd_daemon_reload
    - portal_restart_services

- name: Add uwsgi configuration
  template:
    src: "templates/ini/uwsgi.ini.j2"
    dest: "/etc/uwsgi.ini"
    owner: root
    group: root
    mode: 0644
  notify: portal_restart_services

- name: Start uwsgi.service
  service:
    name: uwsgi
    state: started
    enabled: true
