---
slate_debug: false

slate_hostname: "portal.slateci.io"

slate_git:
  repo: "https://github.com/slateci/slate-portal.git"
  dest: "{{ slate_install.dest }}/slate-website-python"
  version: master

slate_install:
  dest: "/etc/slate"
