---
slate_hostname: "portal.slateci.io"
slate_debug: false
certbot_testmode: true

slate_install_dest: "/etc/slate"
slate_git_dest: "{{ slate_install_dest }}/slate-website-python"
slate_git_version: master

slate_portal_client_id: "XXXX"
slate_portal_client_secret: "XXXX"

slate_api_token: "XXXX"
slate_api_endpoint: "https://api.slateci.io:443"

certbot_admin_email: "slateci-ops@googlegroups.com"
certbot_webroot: "{{ slate_install_dest }}/.well-known"
certbot_create_command: >-
  certbot certonly --webroot
  {{ '--test-cert' if certbot_testmode else '' }}
  --noninteractive --agree-tos
  --email {{ certbot_admin_email }}
  --webroot-path {{ certbot_webroot }}
  -d {{ slate_hostname }}

certbot_auto_renew: true
certbot_auto_renew_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
certbot_auto_renew_hour: "3"
certbot_auto_renew_minute: "30"
certbot_auto_renew_options: "--quiet --no-self-upgrade"
