---
slate_debug: false
slate_hostname: "portal.slateci.io"
slate_portal:
  repo: "https://github.com/slateci/slate-portal.git"
  path: "{{ slate_root.path }}/slate-website-python"
slate_root:
  path: "/etc/slate"
