---
- hosts: all
  become: yes
  become_user: root

  vars_files:
    - defaults.yml

  pre_tasks:
    - name: Set SSL certs path
      set_fact:
        slate_certificate:
          file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.pem"
          key_file: "/etc/ssl/{{slate_hostname}}/{{ slate_hostname }}.key"
          chain_file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.csr"

  tasks:
    - name: OS Packages
      include_tasks:
        file: "./tasks/os-packages.yml"

    - name: Firewall
      include_tasks:
        file: "./tasks/firewalld.yml"

    - name: SELinux
      include_tasks:
        file: "./tasks/selinux.yml"

    - name: Setting Ansible Python Interpreter to Python3
      set_fact:
        ansible_python_interpreter: "/bin/python3"

    - name: Pip
      include_tasks:
        file: "./tasks/pip.yml"

    - name: Self-signed Certificates
      include_tasks:
        file: "./tasks/certs-selfsigned.yml"

    - name: Nginx Configuration
      include_tasks:
        file: "./tasks/nginx.yml"

    - name: SLATE Portal
      include_tasks:
        file: "./tasks/slate.yml"

    - name: uWSGI Configuration
      include_tasks:
        file: "./tasks/uwsgi.yml"

    - name: Set up LetsEncrypt Certs
      block:
        - name: Set SSL certs path
          set_fact:
            slate_certificate:
              file: "/etc/letsencrypt/live/{{ slate_hostname }}/cert.pem"
              key_file: "/etc/letsencrypt/live/{{ slate_hostname }}/privkey.pem"
              chain_file: "/etc/letsencrypt/live/{{ slate_hostname }}/chain.pem"
        - name: LetsEncrypt Certificates
          include_tasks:
            file: "./tasks/certs-letsencrypt.yml"
      when: not slate_debug

  handlers:
    - name: Force systemd to re-read configs
      systemd:
        daemon_reload: yes
      listen: systemd_daemon_reload

    - name: Restart uwsgi.service
      service:
        name: uwsgi
        state: restarted
      listen: portal_restart_services

    - name: Restart nginx.service
      service:
        name: nginx
        state: restarted
      listen: portal_restart_services
