---
- become: yes
  hosts: all
  remote_user: root

  vars_files:
    - defaults.yml

  pre_tasks:
    - name: Set SSL certs path
      set_fact:
        slate_certificate:
          file: "/etc/letsencrypt/live/{{ slate_hostname }}/cert.pem"
          key_file: "/etc/letsencrypt/live/{{ slate_hostname }}/privkey.pem"
          chain_file: "/etc/letsencrypt/live/{{ slate_hostname }}/chain.pem"
      when: not slate_debug

    - name: Set SSL certs path
      set_fact:
        slate_certificate:
          file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.pem"
          key_file: "/etc/ssl/{{slate_hostname}}/{{ slate_hostname }}.key"
          chain_file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.csr"
      when: slate_debug

  tasks:
    - name: SELinux
      include_tasks:
        file: "./tasks/selinux.yml"

    - name: OS Packages and Python3
      include_tasks:
        file: "./tasks/os-packages.yml"

    - set_fact:
        ansible_python_interpreter: "/bin/python3"

    - name: Users and Groups
      include_tasks:
        file: "./tasks/users-groups.yml"

    - name: Pip
      include_tasks:
        file: "./tasks/pip.yml"

    - name: Certificates
      include_tasks:
        file: "./tasks/certs-selfsigned.yml"
      when: slate_debug

    - name: SLATE Portal
      include_tasks:
        file: "./tasks/slate.yml"

    - name: NGINX Configuration
      include_tasks:
        file: "./tasks/nginx.yml"

    - name: uWSGI Configuration
      include_tasks:
        file: "./tasks/uwsgi.yml"

  handlers:
    - name: Systemd
      include_tasks:
        file: "./tasks/systemd-services.yml"
      listen: "restart portal services"
