apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: {{ printf "%s-backendconfig" (include "helm-slate-portal.fullname" .) }}
spec:
  connectionDraining:
    drainingTimeoutSec: 60
  healthCheck:
    checkIntervalSec: 60
    timeoutSec: 10
    healthyThreshold: 2
    unhealthyThreshold: 2
    type: HTTP
    requestPath: /healthz
    port: {{ .Values.portalPort }}
  logging:
    enable: true
    sampleRate: 1
