apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ printf "%s-certificate" (include "helm-slate-portal.fullname" .) }}
  namespace: {{ .Release.Namespace }}
spec:
  domains:
    - {{ .Values.portalEndpoint }}
