apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: slate-instrumentation
spec:
  exporter:
    endpoint: {{ .Values.opentelemetryCollector }}
  propagators:
    - tracecontext
    - baggage
    - b3
  sampler:
    type: parentbased_traceidratio
    argument: "0.25"
  python:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-python:latest
