apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" (include "helm-slate-portal.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-slate-portal.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/app-protocols: '{"portal-port":"HTTP"}'
    cloud.google.com/backend-config: '{"ports": {"portal-port":"{{ printf "%s-backendconfig" (include "helm-slate-portal.fullname" .) }}"}}'
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: portal-port
      protocol: TCP
      targetPort: {{ .Values.portalPort }}
  selector:
    {{- include "helm-slate-portal.selectorLabels" . | nindent 4 }}
