name: Development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches: [ 117-automate-development-pipeline ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # Name of the job
    name: Build the thingie
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # The environment for the job
    environment:
      name: development
      url: https://portal-dev.slateci.io
    # All steps will run in the same shell.
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up Ansible
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: chpc-ansible
          auto-activate-base: false
          environment-file: ./ansible/environment.yml

      - name: Lint Ansible Playbook
        run: |
          cd ./ansible
          ansible-lint --force-color -p

      - name: Build pretend-secrets.yml
        run: |
          mv ./ansible/secrets.yml.tmpl ./ansible/pretend-secrets.yml
          sed -i 's/mailgun_api_token:.*/mailgun_api_token: "${{ secrets.MONEY_BANANA_STAND }}"/g' ./ansible/pretend-secrets.yml
          sed -i 's/slate_api_token:.*/slate_api_token: "banana"/g' ./ansible/pretend-secrets.yml
          sed -i 's/slate_portal_client_id:.*/slate_portal_client_id: "banana"/g' ./ansible/pretend-secrets.yml
          sed -i 's/slate_portal_client_secret:.*/slate_portal_client_secret: "banana"/g' ./ansible/pretend-secrets.yml
          cat ./ansible/pretend-secrets.yml
