name: Development

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the specified branch
  push:
    branches: [ 117-automate-development-pipeline ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repo
        uses: actions/checkout@v2

      # Set up Ansible via Conda
      - name: Set up Ansible
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: chpc-ansible
          auto-activate-base: false
          environment-file: ./ansible/environment.yml

      # Print out stuff
      - name: Debugging info
        run: |
          conda info
          conda list
