name: Integration Tests

on:
  push:
    branches:
      - feature/119_update-regression-tests-to
#      - develop
#      - master

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-20.04

    steps:
      - name: Set up MiniSLATE...
        run: |
          git clone --branch master https://github.com/slateci/minislate.git
          cd minislate/
          rm config.py
          cat > config.py <<EOF
          # start config
          dockerimage = 'hub.opensciencegrid.org/slate/minislate:1.0.4'
          portalbranch = '$GITHUB_REF_NAME'
          # end config
          EOF
          cat config.py
          ./minislate build
          ./minislate init --selenium
          wget -q --spider http://localhost:5050
          if [ $? -ne 0 ] ; then
            echo "MiniSLATE is not up!"
            exit 1
          fi

      - name: Download Selenium tests...
        run: |
          git clone https://github.com/slateci/portal-unit-test.git

      - name: Run Selenium tests...
        uses: docker://hub.opensciencegrid.org/slate/python-chromedriver-selenium:3.9-alpine
        with:
          entrypoint: python
          args: /github/workspace/portal-unit-test/main.py

#      - name: Run Selenium Tests
#        run:
#          python portal-unit-test/main.py

      # Return result to Slack if tests failed
#      - name: Notify Slack Fail
#        if: failure()
#        id: slack # IMPORTANT: reference this step ID value in future Slack steps
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#        uses: voxmedia/github-action-slack-notify-build@v1
#        with:
#          channel_id: CLRGHCWG3
#          status: FAILED
#          color: danger
