name: Integration Tests

on:
  push:
    branches:
      - feature/153_integration-tests-cannot-run-on-github-runner

env:
  KIND_VERSION: v0.14.0
  KUBECTL_VERSION: v1.22.10
  PYTHON_VERSION: 3.9.7

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-20.04

    services:
      chrome:
        image: selenium/standalone-chrome:latest

    steps:
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          cluster_name: test-cluster
          kubectl_version: ${{ env.KUBECTL_VERSION }}
          version: ${{ env.KIND_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            selenium

      - name: Initialize MiniSLATE
        run: |
          git clone --branch develop https://github.com/slateci/minislate.git
          cd minislate/
          rm config.py
          cat > config.py <<EOF
          # start config
          dockerimage = 'hub.opensciencegrid.org/slate/minislate:1.0.5'
          portalbranch = '$GITHUB_REF_NAME'
          # end config
          EOF
          cat config.py
          ./minislate build
          ./minislate init
          ./minislate slate cluster list

      - name: Download Selenium tests
        run: git clone https://github.com/slateci/portal-unit-test.git

      - name: Run Selenium tests
        run: python portal-unit-test/main.py

      # Return result to Slack if tests failed
#      - name: Notify Slack Fail
#        if: failure()
#        id: slack # IMPORTANT: reference this step ID value in future Slack steps
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#        uses: voxmedia/github-action-slack-notify-build@v1
#        with:
#          channel_id: CLRGHCWG3
#          status: FAILED
#          color: danger
