name: Integration Tests

on:
  push:
    branches:
      - feature/153_integration-tests-cannot-run-on-github-runner

env:
  PYTHON_VERSION: 3.9.7

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-20.04

    services:
      chrome:
        image: selenium/standalone-chrome:latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            selenium

      - name: Check out MiniSLATE
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./minislate
          ref: refs/heads/master
          repository: slateci/minislate

      - name: Initialize MiniSLATE
        working-directory: ./minislate
        run: |-
          rm config.py
          cat > config.py <<EOF
          dockerimage = "minislate:local"
          portalbranch = "${{ github.ref_name }}"
          EOF
          ./minislate build
          ./minislate init
          ./minislate slate cluster list

      - name: Check out tests
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./tests
          ref: refs/heads/master
          repository: slateci/portal-unit-test

      - name: Run tests
        working-directory: ./tests
        run: |-
          python main.py
