name: Integration Tests

on:
  push:
    branches:
      - feature/153_integration-tests-cannot-run-on-github-runner

env:
  KIND_VERSION: v0.14.0
  KUBECTL_VERSION: v1.21.10
  PYTHON_VERSION: 3.9.7
  SELENIUM_VERSION: 4.2.0

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-20.04

    services:
      chrome:
        image: selenium/standalone-chrome:latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./checkout

      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          cluster_name: sandbox
          config: ./checkout/.github/resources/kind/config.yml
          kubectl_version: ${{ env.KUBECTL_VERSION }}
          node_image: kindest/node:${{ env.KUBECTL_VERSION }}
          version: ${{ env.KIND_VERSION }}

      - name: Store Kind Kubeconfig
        run: |-
          mkdir -p rancher/k3s
          echo "Pretending Kind KUBECONFIG is Rancher K3s for backwards compatibility..."
          kind get kubeconfig --name=sandbox > ./rancher/k3s/k3s.yaml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            selenium==${{ env.SELENIUM_VERSION }}

      - name: Check out MiniSLATE
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./minislate
          ref: refs/heads/master
          repository: slateci/minislate

      - name: Initialize MiniSLATE
        working-directory: ./minislate
        run: |-
          rm config.py
          echo "Configuring MiniSLATE to use ${{ github.ref_name }}..."
          cat > config.py <<EOF
          dockerimage = "minislate:local"
          portalbranch = "${{ github.ref_name }}"
          EOF

          rm docker-compose.yml.tmpl
          echo "Removing Rancher K3s from Docker Compose file..."
          cat > docker-compose.yml.tmpl <<EOF
          version: "3.9"
          services:
            db:
              image: dwmkerr/dynamodb
              network_mode: "bridge"
              restart: always
            slate:
              depends_on:
                - db
              image: {IMAGE}
              command: /usr/bin/supervisord -c /etc/supervisord.conf
              network_mode: "bridge"
              restart: always
              volumes:
                - ../rancher:/etc/rancher
              ports:
                - 5050:5050
                - 5100:5100
                - 18080:18080
          volumes:
            nfsdata:
          EOF
          cat docker-compose.yml.tmpl

          ./minislate build
          ./minislate init
          ./minislate slate cluster list

      - name: Check Docker containers
        run: |-
          docker container ls --all

      - name: Check out tests
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./tests
          ref: refs/heads/master
          repository: slateci/portal-unit-test

      - name: Run tests
        working-directory: ./tests
        run: |-
          python main.py
