name: Integration Tests

on:
  push:
    branches:
      - feature/119_update-regression-tests-to
#      - develop
#      - master

jobs:
  test:
    name: Selenium Tests
    runs-on: ubuntu-20.04
    container:
      image: hub.opensciencegrid.org/slate/python-chromedriver-selenium:3.9-alpine

    steps:
      - name: Set up MiniSLATE...
        run: |
          git clone --branch master https://github.com/slateci/minislate.git
          cd minislate/
          sed -i 's@portalbranch =.*@portalbranch = "${{ github.ref.name }}"@g' config.py
          cat config.py
          ./minislate build
          ./minislate init --selenium

      - name: Download Selenium tests...
        run: |
          git clone https://github.com/slateci/portal-unit-test.git

      - name: Run Selenium Tests
        run:
          python portal-unit-test/main.py

      # Return result to Slack if tests failed
#      - name: Notify Slack Fail
#        if: failure()
#        id: slack # IMPORTANT: reference this step ID value in future Slack steps
#        env:
#          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
#        uses: voxmedia/github-action-slack-notify-build@v1
#        with:
#          channel_id: CLRGHCWG3
#          status: FAILED
#          color: danger
