name: Integration Tests

on:
  push:
    branches:
      - feature/153_integration-tests-cannot-run-on-github-runner

env:
  KIND_VERSION: v0.14.0
  KUBECTL_VERSION: v1.22.10
  PYTHON_VERSION: 3.9.7

jobs:
  selenium:
    name: Selenium Tests
    runs-on: ubuntu-20.04

    services:
      chrome:
        image: selenium/standalone-chrome:latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Portal image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./resources/docker/Dockerfile
          target: release-stage
          push: false
          tags: "slate_portal:local"

      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          config: ./.github/resources/kind/config.yml
          kubectl_version: ${{ env.KUBECTL_VERSION }}
          version: ${{ env.KIND_VERSION }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Python packages
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            selenium

      - name: Check out Selenium tests
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./tests
          ref: refs/heads/master
          repository: slateci/portal-unit-test

      - name: Run Selenium tests
        working-directory: ./tests
        run: python main.py
