---
- name: Create group for running uwsgi
  group:
    name: uwsgi
    state: present
- name: Create user for running uwsgi
  user:
    name: uwsgi
    state: present
    shell: /sbin/nologin
    group: uwsgi
    home: /var/run/uwsgi
    system: true
- name: Install epel-release via system package manager
  package:
    name: epel-release
    state: present
- name: Install uwsgi packages/dependencies via system package manager
  package:
    name:
      - uwsgi
      - uwsgi-plugin-python2
    state: present
- name: Add systemd uwsgi configuration
  template:
    src: "templates/uwsgi.service.j2"
    dest: "/etc/systemd/system/uwsgi.service"
    owner: root
    group: root
    mode: 0644
- name: Add uwsgi configuration
  template:
    src: "templates/uwsgi.ini.j2"
    dest: "/etc/uwsgi.ini"
    owner: root
    group: root
    mode: 0644
- name: Start and enable the uwsgi service
  service:
    name: "uwsgi"
    state: started
    enabled: true
